#!/usr/bin/env bash

set -e

if [ "$(uname -s)" = "Darwin" ]; then
  CONFIG="install_configs/osx.conf.yaml"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
  CONFIG="install_configs/windows.conf.yaml"
else
  CONFIG="install_configs/generic.conf.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
