set nocompatible
filetype off

" Setup for vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Keep vundle itself updated
Plugin 'gmarik/vundle'

" Syntax plugins
Plugin 'JuliaLang/julia-vim'
Plugin 'keith/swift.vim'
" Plugin 'garbas/vim-snipmate'
" Plugin 'honza/vim-snippets'
" Plugin 'MarcWeber/vim-addon-mw-utils'
" Plugin 'tomtom/tlib_vim'
Plugin 'vim-scripts/a.vim' " Alternate between header files using :A
Plugin 'jansenm/vim-cmake'
Plugin 'beyondmarc/hlsl.vim'
Plugin 'dkprice/vim-easygrep'
Plugin 'tommcdo/vim-kangaroo'

" Generate ctags for project files
Plugin 'vim-scripts/DfrankUtil' " Dependency for VimPrj and Indexer
Plugin 'vim-scripts/indexer.tar.gz'
Plugin 'vim-scripts/vimprj'
Plugin 'majutsushi/tagbar' " Use ctags to show class outline

" Airline - pretty status bar along bottom
Plugin 'bling/vim-airline'
set laststatus=2 " Open on startup

" Syntax checking and completion
Plugin 'Valloric/YouCompleteMe'
let g:ycm_show_diagnostics_ui = 0 " Disable YCM syntax checking
Plugin 'rdnetto/YCM-Generator'
Plugin 'Chiel92/vim-autoformat' " :AutoFormat
Plugin 'scrooloose/syntastic'

" C++ Syntax highlighting
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'kshenoy/vim-signature' " Visualization of marks 

" Tasklist Plugin - use \t to get list of all TODO, FIXME, etc..
Plugin 'vim-scripts/TaskList.vim'
let g:tlTokenList=["FIXME", "TODO", "???", "XXX"]

" Dash - use :Dash to open get dash references
Plugin 'rizzatti/dash.vim'

" Sublime-like Minimap
Plugin 'severin-lemaignan/vim-minimap' " use \mm and \mc

" JSX and Javascript highlighting
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'

" Git plugin
Plugin 'tpope/vim-fugitive' " Use :Gedit :Gstatus :Gdiff :Gcommit
Plugin 'jaxbot/github-issues.vim' " Show issues :Gissues close/open - :co/:cc
Plugin 'airblade/vim-gitgutter'
let g:gitgutter_highlight_lines = 1

" Comments
Plugin 'scrooloose/nerdcommenter' " Use <leader>cc to comment all selected lines and c<space> to toggle
" Folding - for Python
Plugin 'tmhedberg/SimpylFold'

" Nerdtree
Plugin 'scrooloose/nerdtree'
Plugin 'tyok/ack.vim'
Plugin 'tyok/nerdtree-ack'
let g:NERDTreeShowHidden=1 " Show hidden files by default

" CtrlP
Plugin 'ctrlpvim/ctrlp.vim' " Use :CtrlP to search for a file 
let g:ctrlp_working_path_mode = 'rwa' 
noremap <leader>t :CtrlPTag<cr>

" Set colorscheme
" Solarized theme and with Meslo LG S DZ Regular for Powerline 13 pt (iTerm2)
Plugin 'altercation/vim-colors-solarized'
set guifont=Meslo\ LG\ S\ DZ\ Regular\ for\ Powerline:h13 " Font needs to be installed
set background=dark
colorscheme solarized
let macvim_skip_colorscheme=1 " Don't override colorscheme in MacVim
highlight clear SignColumn

" Search settings 
set hlsearch
set incsearch

" Shortcuts
" Ctrl-n opens and closes file tray; Ctrl-f focuses on tray 
map <silent> <C-f> :NERDTreeFocus<CR> 
map <silent> <C-n> :NERDTreeToggle<CR> 

" Ctrl-o opens TagBar
map <silent> <C-o> :TagbarToggle<CR>

" Plugin and indent usage
filetype plugin indent on

" Folding settings
set foldmethod=syntax
set nofoldenable

" Misc. other settings
syntax on
set number
set expandtab
set shiftwidth=2
set softtabstop=2

" Close preview window on movement or entering of insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
