# Dotfiles export
DOTFILES_DIR=$HOME/.dotfiles
export DOTFILES_DIR

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Export QT
export QT_HOME=~/Development/Qt/5.9.2
export QT_PLUGIN_PATH=~/Development/Qt/5.9.2/clang_64/plugins

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git brew osx colored-man zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Check if running on OSX
if [ "$(uname -s)" = "Darwin" ]; then
    OS="OSX"
else
    OS=$(uname -s)
fi
export OS

# Source user configuration
source $DOTFILES_DIR/zsh/zsh-env.sh

# Source RTC configuration
source $DOTFILES_DIR/zsh/rtc-env.sh

# tmux setup
if [ "$TMUX" = "" ]; then tmux; fi
eval "$(tmuxifier init -)"
